---
- name: Auto deploy SSH public key to remote servers
  hosts: all
  become: true
  tasks:
    - name: Ensure ~/.ssh exists
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: 0700
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Upload authorized key
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('env', 'PUBLIC_KEY') }}"
        state: present
